name: electrokart
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 
  lottie:
  flutter_snake_navigationbar:
  english_words: ^4.0.0
  shared_preferences: any
  flutter_html:
  flutter_widget_from_html: ^0.14.11
  flutter_html_table: ^3.0.0-beta.2
  flutter_rating_bar:
  carousel_slider: ^4.0.0
  skeleton_text: ^3.0.1
  persistent_shopping_cart: ^0.0.7
  cached_network_image: ^3.3.1
  hive: ^2.2.3
  qr_flutter: ^4.1.0
  flutter_bounceable: ^1.1.0
  provider: ^6.1.2
#  flutter_checkout_payment: any
#  flutter_credit_card: ^4.0.1
  phonepe_payment_sdk: any
  crypto: ^3.0.3
  google_sign_in: ^6.2.1
#  agora_rtc_engine: ^6.3.2

  qr_image:
  http:
  flutter: 
    sdk: flutter
  fluttertoast: ^8.2.6

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/
    - assets/lottie/iconback.json
    - assets/lottie/
    - assets/images/